name: Fetch Information

on:
  push:
    branches:
      - main
    paths-ignore:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Build
        run: |
          node script.js
      - name: Push Results
        run:  |
          git add .
          git commit -m "Push Auto"
          git push -u origin main
